Feature/126 temporary hide empty tabs
ditrit/leto pull request #145
Opened 2022-06-22 14:18 UTC by BrahimS

Hide Libraries
Hide Requirements
Hide Dashboard
Create an "Under construction" banner in the Home

2022-06-23 11:49 UTC, Zorin95670 requested changes

2022-06-23 11:49 UTC, Zorin95670 commented on frontend/src/pages/Home/PageHomeWorkspaces.vue
> +		<q-banner inline-actions rounded class="bg-orange text-white">
Replace this 

```html
<q-banner inline-actions rounded class="bg-orange text-white">
  <spam style="font-size: 1.2em">
    The workspace page is under construction
  </spam>
</q-banner>
```

by

```
<q-banner inline-actions rounded class="bg-orange text-white">
      <template v-slot:avatar>
        <q-icon name="account-hard-hat" color="white" />
      </template>
      This page is under construction.
</q-banner>
```

2022-06-29 10:13 UTC, BrahimS commented on frontend/src/pages/Home/PageHomeWorkspaces.vue
> +		<q-banner inline-actions rounded class="bg-orange text-white">
Done

2022-06-29 15:29 UTC, BrahimS commented on frontend/src/pages/Home/PageHomeWorkspaces.vue
> +		<q-banner inline-actions rounded class="bg-orange text-white">
Ok

2022-07-20 07:48 UTC, closed without merging