Feature/compile on switch
ditrit/leto pull request #196
Opened 2022-07-01 14:39 UTC by BrahimS

Migrate all the logics of the text editor to PageProductChild.vue and compile on switch.
TODO in the futur: 
1 - update to composition API
2 - Create a composable file with all the logics for text editor.

2022-07-04 08:26 UTC, Zorin95670 requested changes

2022-07-04 08:26 UTC, Zorin95670 commented on frontend/src/pages/Products/PageProductChild.vue
> +			console.log("this.iactorDatas: ", this.iactorDatas);
Remove all `console.log`.

2022-07-04 09:03 UTC, BrahimS commented on frontend/src/pages/Products/PageProductChild.vue
> +			console.log("this.iactorDatas: ", this.iactorDatas);
ok

2022-07-04 14:58 UTC, Mari0nV requested changes
There is a bug when we compile a file twice:

https://user-images.githubusercontent.com/23618241/177179493-f5485651-1fab-4215-bdc6-0df942ce2c65.mp4

2022-07-04 14:58 UTC, AlexisNeveu approved these changes

2022-07-04 15:29 UTC, BrahimS commented
@marion. voila le bug est fixé : https://nextcloud.ditrit.io/index.php/s/bqcX7R2aB9jg9qL

2022-07-04 15:49 UTC, Mari0nV commented
I see other bugs: 
- When changing the content of Text, the Model 3D does not show the changes immediately.
- When adding a component in the Model 3D, it does not change the Text.

I tested all of this in demo-4-july on Mozilla and these problems were not there.

https://user-images.githubusercontent.com/23618241/177187276-6e5a9a14-11e5-4ac9-bfa8-d65dbc42152e.mp4

2022-07-07 16:52 UTC, Mari0nV commented
I still see a bug that I don't have on demo-4-july:

https://user-images.githubusercontent.com/23618241/177828122-311bb48e-b4ab-4c94-a42c-b2b9202fe479.mp4

The aws instance is not displayed in the Model 3D view although it's present on the Text view

2022-07-07 17:38 UTC, BrahimS commented
[Demo](https://user-images.githubusercontent.com/7687826/177835713-8f9c9140-fdcb-435b-a68f-a5e706ca9e11.webm)

2022-07-11 09:47 UTC, Zorin95670 approved these changes

2022-07-11 10:09 UTC, merged