Improvement/modelization adding config panel function
ditrit/leto pull request #79
Opened 2022-06-07 07:44 UTC by AlexisNeveu

2022-06-07 12:42 UTC, BrahimS reviewed
WIP = work in progress.
Try that the message of your commit, briefly describe the changes to your code

2022-06-07 12:42 UTC, BrahimS submitted a review, later dismissed

2022-06-07 12:49 UTC, BrahimS reviewed
You can combine this [commit](https://github.com/ditrit/leto/pull/79/commits/1fe7def5650db4f913b3ca1d16f25ad4d6179ee2) with this [one](https://github.com/ditrit/leto/pull/79/commits/d2d859cd6adcca9199783ca214f3af5cf9365b12)

2022-06-07 14:44 UTC, Zorin95670 commented
I'm sorry @BrahimS, But I already told to @AlexisNeveu the problem of it's commit :)
My bad I forgot to add a comment on github .

2022-06-08 10:04 UTC, Zorin95670 requested changes

2022-06-08 10:04 UTC, Zorin95670 commented on frontend/src/components/2DModel/ToscaObjectNode.js
> +	setContainer_height(height){
camelCase not _ :)

2022-06-08 10:04 UTC, Zorin95670 commented on frontend/src/components/2DModel/utils.js
> +import ToscaObjectNode from "./ToscaObjectNode";
rename commit:

`Using LetoObjectNode instead of js object`

2022-06-08 10:04 UTC, Zorin95670 commented on frontend/src/components/2DModel/Modelization.vue
> +		function show_infos() {
No underscore in function name

2022-06-08 10:04 UTC, Zorin95670 commented on frontend/src/components/2DModel/Modelization.vue
> +				console.log("click "+this.parentNode.parentNode.parentNode.getAttribute("id"));
Remove console log

2022-06-08 10:04 UTC, Zorin95670 commented on frontend/src/components/2DModel/Modelization.vue
> +				function traverseData(node){
No function inside function

2022-06-08 10:04 UTC, Zorin95670 commented on frontend/src/components/2DModel/Modelization.vue
> +				if (node == null) return;
always keep the {} with an if or if else
```js
// BAD
if (...) return;

if () X
else {
X
}
// Good
if (){
 B
}


if () {
D
} else {
E
}
```

2022-06-09 12:43 UTC, Zorin95670 approved these changes

2022-06-09 12:43 UTC, merged